default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: # デフォルトだと空欄になっているはずなので変更
  host: localhost # デフォルトだとlocalhostになっているはずなので変更

development:
  <<: *default
  database: L-STORE_development

test:
  <<: *default
  database: L-STORE_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  socket: /var/lib/mysql/mysql.sock